version: "3.7"

services:

  scheduler-test:
    build: ./scheduler
    container_name: scheduler-test
    # command: /bin/bash -c "python3 run.py"
    # command: /bin/bash -c "uwsgi app.ini"
    command: /bin/bash -c "pytest"
    # restart: always
    volumes:
      - ./scheduler:/app
      - ~/.aws:/root/.aws
    environment:
      - APP_NAME=MyFlaskApp
    # ports:
    #   - "8080:8080"
    expose:
      - 8080

  scheduler-dev:
    build: ./scheduler
    container_name: scheduler-dev
    command: /bin/bash -c "python3 run.py"
    # command: /bin/bash -c "uwsgi app.ini"
    # command: /bin/bash -c "pytest; exit 1"
    # restart: always
    volumes:
      - ./flask:/app
      - ~/.aws:/root/.aws
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - "8080:8080"
    # expose:
    #   - 8080

  scheduler-prod:
    build: ./scheduler
    container_name: scheduler-prod
    # command: /bin/bash -c "python3 run.py"
    command: /bin/bash -c "uwsgi app.ini"
    # command: /bin/bash -c "pytest; exit 1"
    restart: always
    volumes:
      - ./scheduler:/app
      - ~/.aws:/root/.aws
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    depends_on:
      - nginx

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    # depends_on:
    #   - scheduler-prod