version: '3'
services:
  scheduler-dev:
    build: .
    command: python3 run.py
    volumes: 
      - .:/usr/src/app
      - ~/.aws:/root/.aws
    ports:
      - 80:80
  scheduler-test:
    build: .
    command: pytest
    volumes: 
      - .:/usr/src/app
      - ~/.aws:/root/.aws


