version: '3.5'
services:
  scheduler-dev:
    container_name: scheduler-dev
    build:
      context: .
      # target: dev
    command: python3 run.py
    volumes: 
      - .:/usr/src/app
      - ~/.aws:/root/.aws
    ports:
      - 80:80
  scheduler-test:
    container_name: scheduler-test
    build:
      context: .
      # target: dev
    command: pytest
    volumes: 
      - .:/usr/src/app
      - ~/.aws:/root/.aws
  # scheduler-prod:
  #   container_name: scheduler-prod
  #   build:
  #     context: .
  #     target: prod
  #   # command: pytest
  #   volumes: 
  #     - .:/app
  #     - ~/.aws:/root/.aws
  #   ports:
  #     - 5000:5000
  #   # links:
  #   #   - scheduler-nginx
  #   expose:
  #     - 8080
  # scheduler-nginx:
  #   container_name: scheduler-nginx
  #   build:
  #     context: .
  #     target: nginx
  #   restart: always
  #   # volumes: 
  #     # - .:/app
  #     # - ~/.aws:/root/.aws
  #   ports:
  #     - 8000:80
  #   depends_on:
  #     - scheduler-prod




