version: '3'
services:
  scheduler:
    build: .
    volumes: 
      - .:/usr/src/app
      - ~/.aws:/root/.aws
    ports:
      - 8080:8080
      - 8081:8081
    environment:
     - AWS_DEFAULT_PROFILE=nubank
